### PR TITLE
added R.utils to geospatial_plus builds

### PR DESCRIPTION
**Pull request by lpiep**

### CODE REVIEW

**Comment by myoung3** [comment]
@lpiep Looks like the precommit hook didn't run. Either you made the change through github.com or else you didn't set up the pre-commit hooks. 

Try again by pulling the repo to the server, checking out a new branch from main, then making the change on the new branch. 
Commit the change, and push the new branch to github.com, then start a pull request using the github.com interface from that branch.

**Comment by myoung3** [comment]
ok good looks like you were able to run the hook on this branch. Watch the build progress to see if this is successful. It may fail at the end since it uses your github account to push to this repo's container registry (and your account might not have the right permissions set up for this repo), but since you're an admin account for the team my guess is that it will work.

**Comment by myoung3** [comment]
@lpiep ok the dev image failed to get uploaded to packages (only dev images get uploaded on pull requests--the 4.1.0 images just get build but not uploaded). This suggests a user permissions issue. I've explicitly added you as a user on this repo which will hopefully fix this. Try again by making a white-space only change to the geospatial_plus %post file (and make sure the pre-commit hooks run on it).

**Comment by myoung3** [comment]
(a couple of things worth explaining):

1) the build process starts for every commit on a PR, but images only get built for definition files that have changed. hence the white-space only change to restart the builds.

2) only images which are the dev tag get deployed to the container registry for commits on a PR. all images are build, but only dev images are deployed. when a PR gets merged to master the images are rebuilt then actually deployed. this makes it so stable (version-tagged images) don't get messed with in PRs (with the exception of images with dev tags which should be assumed to be unstable).

**Comment by myoung3** [comment]
Looks like this is still having access issues. Can you try the following code on mesa3? Replace *** with a github access token that has the ability to push to packages, and replace output.sif with an arbitrary sif file:

```
echo *** | singularity remote login -u lpiep --password-stdin oras://ghcr.io
  singularity remote list
  singularity push output.sif oras://ghcr.io/kaufman-lab/geospatial_plus_ml_horovod:dev 
```

**Comment by myoung3** [comment]
If the above code works, then it might mean the issue is that you're trying to do a PR from a fork (I'm pretty sure github disables giving secrets to forks, even if you have write access to the forked repo). Try closing this PR, then creating a new branch on a clone of this repo, then pushing that branch to this repo and initiating a PR from that branch on github.com

**Comment by myoung3** [comment]
fyi this is the relevant line from the action:
https://github.com/kaufman-lab/build_containers/blob/39309599c4ff110e30b6ed62c2b8f08172fff852/.github/workflows/build_containers.yml#L163

**Comment by lpiep** [comment]
Closing this pull request because of the authentication issues noted. Will submit an identical request as a branch of the main repo.

**Pull request closed without merging**
